=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/objects/object.dtd
<!ELEMENT OBJECTSHAPE (VERTICES,NORMALS,UVS,TRIANGLES,TEXTUREFILE)>

<!ELEMENT VERTICES (VERTEX)*>
<!ELEMENT NORMALS (NORMAL)*>
<!ELEMENT UVS (UV)*>
<!ELEMENT TRIANGLES (TRIANGLE)*>
<!ELEMENT TEXTUREFILE EMPTY>

<!ELEMENT VERTEX EMPTY>
<!ELEMENT NORMAL EMPTY>
<!ELEMENT UV EMPTY>

<!ATTLIST OBJECTSHAPE num_v		CDATA	#REQUIRED>
<!ATTLIST OBJECTSHAPE num_n		CDATA	"-1">
<!ATTLIST OBJECTSHAPE num_uv		CDATA	"-1">
<!ATTLIST OBJECTSHAPE num_t		CDATA	"-1">
<!ATTLIST VERTEX n			CDATA	#REQUIRED>
<!ATTLIST VERTEX x			CDATA	#REQUIRED>
<!ATTLIST VERTEX y			CDATA	#REQUIRED>
<!ATTLIST VERTEX z			CDATA	#REQUIRED>
<!ATTLIST NORMAL n			CDATA	#REQUIRED>
<!ATTLIST NORMAL x			CDATA	#REQUIRED>
<!ATTLIST NORMAL y			CDATA	#REQUIRED>
<!ATTLIST NORMAL z			CDATA	#REQUIRED>
<!ATTLIST UV n				CDATA	#REQUIRED>
<!ATTLIST UV x				CDATA	#REQUIRED>
<!ATTLIST UV y				CDATA	#REQUIRED>

<!ATTLIST TRIANGLE n			CDATA	#REQUIRED>
<!ATTLIST TRIANGLE v1			CDATA	#REQUIRED>
<!ATTLIST TRIANGLE v2			CDATA	#REQUIRED>
<!ATTLIST TRIANGLE v3			CDATA	#REQUIRED>
<!ATTLIST TRIANGLE n1			CDATA	"-1">
<!ATTLIST TRIANGLE n2			CDATA	"-1">
<!ATTLIST TRIANGLE n3			CDATA	"-1">
<!ATTLIST TRIANGLE uv1			CDATA	"-1">
<!ATTLIST TRIANGLE uv2			CDATA	"-1">
<!ATTLIST TRIANGLE uv3			CDATA	"-1">

<!ATTLIST TEXTUREFILE path		CDATA	#REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/objects/roof.xml
<?xml version="1.0"?>
<!DOCTYPE OBJECTSHAPE SYSTEM "object.dtd" []>
<OBJECTSHAPE num_v="4" num_n="1" num_uv="4" num_t="2">
<VERTICES>
<VERTEX n="0" x="-1000" y="300" z="-1000"/>
<VERTEX n="1" x="1000" y="300" z="-1000"/>
<VERTEX n="2" x="1000" y="300" z="1000"/>
<VERTEX n="3" x="-1000" y="300" z="1000"/>
</VERTICES>
<NORMALS>
<NORMAL n="0" x="0" y="-1" z="0"/>
</NORMALS>
<UVS>
<UV n="0" x="0" y="0"/>
<UV n="1" x="10" y="0"/>
<UV n="2" x="10" y="10"/>
<UV n="3" x="0" y="10"/>
</UVS>
<TRIANGLES>
<TRIANGLE n="0" v1="0" v2="1" v3="3" n1="0" n2="0" n3="0" uv1="0" uv2="1" uv3="3"/>
<TRIANGLE n="1" v1="1" v2="2" v3="3" n1="0" n2="0" n3="0" uv1="1" uv2="2" uv3="3"/>
</TRIANGLES>
<TEXTUREFILE path="plaster2.bmp"/>
</OBJECTSHAPE>
