=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/analysisrules.dtd
<!ELEMENT analysisrules (rule*)>
	
<!ELEMENT rule (ifthen|modify)*>
<!ATTLIST rule
	name CDATA #REQUIRED>

<!ELEMENT ifthen (condition+, modify+)>

<!ELEMENT condition (parameter|operator|value)*>

<!ELEMENT modify (parameter|operator|value)*>

<!ELEMENT parameter ANY>

<!ELEMENT operator ANY>

<!ELEMENT value ANY>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/analysisrules.xml
<?xml version="1.0"?>
<!DOCTYPE analysisrules SYSTEM "analysisrules.dtd" []>

<analysisrules>

	<rule name="HEAD_NOD">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_nod</value>
		</modify>
	</rule>

	<rule name="HEAD_NOD_FAST">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_nod_fast</value>
		</modify>
	</rule>

	<rule name="HEAD_NOD_SLOW">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_nod_slow</value>
		</modify>
	</rule>

	<rule name="HEAD_SHAKE">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_shake</value>
		</modify>
	</rule>

	<rule name="HEAD_UP">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_up</value>
		</modify>
	</rule>

	<rule name="HEAD_DOWN">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_down</value>
		</modify>
	</rule>

	<rule name="HEAD_RIGHT">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_right</value>
		</modify>
	</rule>

	<rule name="HEAD_LEFT">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>head_left</value>
		</modify>
	</rule>

	<rule name="SMILE">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>smile</value>
		</modify>
	</rule>
	
	<rule name="OPENSMILE">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>opensmile</value>
		</modify>
	</rule>

	<rule name="RAISE">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>raise</value>
		</modify>
	</rule>

	

	<rule name="NODSMILE">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>nodsmile</value>
		</modify>
	</rule>
	
	<rule name="NODOPEN">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>nodopen</value>
		</modify>
	</rule>

	<rule name="NODRAISE">			
		<modify>
			<parameter>NAME</parameter> 
			<operator>SET</operator>
			<value>nodraise</value>
		</modify>
	</rule>



	<rule name="NODS">
		<ifthen>
			<condition>
				<parameter>STATE</parameter> 
				<operator>EQUAL</operator>
				<value>1</value>
			</condition>			
			<modify>
				<parameter>NAME</parameter> 
				<operator>SET</operator>
				<value>head_nod</value>
			</modify>
		</ifthen>
	
		<ifthen>
			<condition>
				<parameter>STATE</parameter> 
				<operator>EQUAL</operator>
				<value>-1</value>
			</condition>
			<modify>
				<parameter>NAME</parameter> 
				<operator>SET</operator>
				<value>head_shake</value>
			</modify>
		</ifthen>
	</rule>

	<rule name="POSES">
		<modify>
			<parameter>RX</parameter>
			<operator>SET</operator>
			<value>rotation_x</value>
		</modify>
		<modify>
			<parameter>RY</parameter>
			<operator>SET</operator>
			<value>rotation_y</value>
		</modify>
		<modify>
			<parameter>RZ</parameter>
			<operator>SET</operator>
			<value>rotation_z</value>
		</modify>
		<modify>
			<parameter>TX</parameter>
			<operator>SET</operator>
			<value>traslation_x</value>
		</modify>
		<modify>
			<parameter>TY</parameter>
			<operator>SET</operator>
			<value>traslation_y</value>
		</modify>
		<modify>
			<parameter>TZ</parameter>
			<operator>SET</operator>
			<value>traslation_z</value>
		</modify>
	</rule>
	
</analysisrules>
