=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/dtd/expression.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT expression (char, face, cons)>
<!ATTLIST expression
	name CDATA #REQUIRED
>
<!ELEMENT char (emotion?, profile?, time?, intensity?, desciption?)>
<!ELEMENT emotion EMPTY>
<!ATTLIST emotion
	name CDATA #REQUIRED
>
<!ELEMENT profile EMPTY>
<!ATTLIST profile
	name CDATA #IMPLIED
>
<!ELEMENT time EMPTY>
<!ATTLIST time
	min CDATA #IMPLIED
	max CDATA #IMPLIED
>
<!ELEMENT intensity EMPTY>
<!ATTLIST intensity
	min CDATA #IMPLIED
	max CDATA #IMPLIED
>
<!ELEMENT desciption EMPTY>
<!ATTLIST desciption
	comment CDATA #IMPLIED
	author CDATA #IMPLIED
>
<!ELEMENT face (fap+)>
<!ELEMENT fap EMPTY>
<!ATTLIST fap
	num CDATA #IMPLIED
	value CDATA #IMPLIED
>
<!ELEMENT cons (#PCDATA)>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/very_high_tensed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="very_high_tensed">
	<char>
		<emotion name="tensed"/>
		<profile name="tensed"/>
		<time min="0.5" max="4"/>
		<intensity min="0.75" max="1"/>
		<desciption comment="" author=""/>
	</char>
	<face>
<fap num="3" value="-99"/>
<fap num="6" value="16"/>
<fap num="7" value="16"/>
<fap num="10" value="56"/>
<fap num="11" value="56"/>
<fap num="39" value="-160"/>
<fap num="40" value="-160"/>
<fap num="41" value="120"/>
<fap num="42" value="120"/>
<fap num="51" value="165"/>
<fap num="52" value="198"/>
<fap num="53" value="11"/>
<fap num="54" value="11"/>
<fap num="55" value="99"/>
<fap num="56" value="99"/>
<fap num="57" value="17"/>
<fap num="58" value="17"/>
<fap num="59" value="-50"/>
<fap num="60" value="-50"/>
<fap num="19" value="200"/>
<fap num="20" value="200"/>
<fap num="21" value="100"/>
<fap num="22" value="100"/>
<fap num="31" value="60"/>
<fap num="32" value="60"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/high_fear.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="high_fear">
	<char>
		<emotion name="fear"/>
		<profile name="fear"/>
		<time min="0.5" max="4"/>
		<intensity min="0.5" max="0.75"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="3" value="105"/>
<fap num="5" value="-189"/>
<fap num="10" value="-336"/>
<fap num="11" value="-336"/>
<fap num="12" value="-105"/>
<fap num="13" value="-105"/>
<fap num="51" value="73"/>
<fap num="52" value="-14"/>
<fap num="55" value="63"/>
<fap num="56" value="63"/>
<fap num="57" value="357"/>
<fap num="58" value="518"/>
<fap num="59" value="-105"/>
<fap num="60" value="-105"/>
<fap num="19" value="-200"/>
<fap num="20" value="-200"/>
<fap num="21" value="-100"/>
<fap num="22" value="-100"/>
<fap num="31" value="45"/>
<fap num="32" value="45"/>
<fap num="33" value="90"/>
<fap num="34" value="90"/>
<fap num="35" value="45"/>
<fap num="36" value="45"/>
<fap num="37" value="67"/>
<fap num="38" value="67"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/very_high_anger.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="very_high_anger">
	<char>
		<emotion name="anger"/>
		<profile name="anger"/>
		<time min="0.5" max="4"/>
		<intensity min="0.75" max="1"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="3" value="-90"/>
<fap num="6" value="15"/>
<fap num="7" value="15"/>
<fap num="10" value="51"/>
<fap num="11" value="51"/>
<fap num="51" value="150"/>
<fap num="52" value="180"/>
<fap num="53" value="10"/>
<fap num="54" value="10"/>
<fap num="55" value="90"/>
<fap num="56" value="90"/>
<fap num="57" value="16"/>
<fap num="58" value="16"/>
<fap num="19" value="100"/>
<fap num="20" value="100"/>
<fap num="21" value="216"/>
<fap num="22" value="216"/>
<fap num="31" value="-157"/>
<fap num="32" value="-157"/>
<fap num="33" value="-180"/>
<fap num="34" value="-180"/>
<fap num="35" value="-18"/>
<fap num="36" value="-18"/>
<fap num="37" value="108"/>
<fap num="38" value="108"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/r_low_anger.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="low_anger">
	<char>
		<emotion name="anger"/>
		<profile name="anger"/>
		<time min="0.5" max="4"/>
		<intensity min="0.25" max="0.5"/>
		<desciption comment="" author=""/>
	</char>
	<face>
<fap num="31" value="-122"/>
<fap num="32" value="-122"/>
<fap num="33" value="-140"/>
<fap num="34" value="-140"/>
<fap num="35" value="-14"/>
<fap num="36" value="-14"/>
<fap num="37" value="84"/>
<fap num="38" value="84"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/very_high_joy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="very_high_joy">
	<char>
		<emotion name="joy"/>
		<profile name="joy"/>
		<time min="0.5" max="4"/>
		<intensity min="0.75" max="1"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="4" value="-210"/>
<fap num="5" value="140"/>
<fap num="8" value="-30"/>
<fap num="9" value="-30"/>
<fap num="10" value="-120"/>
<fap num="11" value="-120"/>
<fap num="18" value="60"/>
<fap num="31" value="60"/>
<fap num="32" value="60"/>
<fap num="33" value="85"/>
<fap num="34" value="85"/>
<fap num="35" value="21"/>
<fap num="36" value="21"/>
<fap num="41" value="375"/>
<fap num="42" value="375"/>
<fap num="51" value="-30"/>
<fap num="52" value="150"/>
<fap num="53" value="70"/>
<fap num="54" value="70"/>
<fap num="55" value="-10"/>
<fap num="56" value="-10"/>
<fap num="59" value="210"/>
<fap num="60" value="210"/>
<fap num="19" value="153"/>
<fap num="20" value="153"/>
<fap num="21" value="76"/>
<fap num="22" value="76"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/very_high_sadness.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="very_high_sadness">
	<char>
		<emotion name="sadness"/>
		<profile name="sadness"/>
		<time min="0.5" max="4"/>
		<intensity min="0.75" max="1"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="3" value="105"/>
<fap num="4" value="-45"/>
<fap num="5" value="-60"/>
<fap num="6" value="-40"/>
<fap num="7" value="-40"/>
<fap num="53" value="-32"/>
<fap num="54" value="-32"/>
<fap num="59" value="-130"/>
<fap num="60" value="-130"/>
<fap num="25" value="8722"/>
<fap num="26" value="8722"/>
<fap num="19" value="100"/>
<fap num="20" value="100"/>
<fap num="21" value="50"/>
<fap num="22" value="50"/>
<fap num="31" value="220"/>
<fap num="32" value="220"/>
<fap num="33" value="25"/>
<fap num="34" value="25"/>
<fap num="35" value="5"/>
<fap num="36" value="5"/>
<fap num="37" value="20"/>
<fap num="38" value="20"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/a_very_low_anger.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="very_low_anger">
	<char>
		<emotion name="anger"/>
		<profile name="anger"/>
		<time min="0.5" max="4"/>
		<intensity min="0" max="0.25"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
		<fap num="19" value="70"/>
		<fap num="20" value="70"/>
		<fap num="21" value="168"/>
		<fap num="22" value="168"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/a_very_low_joy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="very_low_joy">
	<char>
		<emotion name="joy"/>
		<profile name="joy"/>
		<time min="0.5" max="4"/>
		<intensity min="0" max="0.25"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="4" value="-45"/>
<fap num="5" value="105"/>
<fap num="18" value="30"/>
<fap num="41" value="95"/>
<fap num="42" value="95"/>
<fap num="51" value="-5"/>
<fap num="52" value="85"/>
<fap num="53" value="35"/>
<fap num="54" value="35"/>
<fap num="55" value="-5"/>
<fap num="56" value="-5"/>
<fap num="59" value="105"/>
<fap num="60" value="105"/>
	</face>
	<cons>
	</cons>
</expression>
