=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/dtd/expression.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT expression (char, face, cons)>
<!ATTLIST expression
	name CDATA #REQUIRED
>
<!ELEMENT char (emotion?, profile?, time?, intensity?, desciption?)>
<!ELEMENT emotion EMPTY>
<!ATTLIST emotion
	name CDATA #REQUIRED
>
<!ELEMENT profile EMPTY>
<!ATTLIST profile
	name CDATA #IMPLIED
>
<!ELEMENT time EMPTY>
<!ATTLIST time
	min CDATA #IMPLIED
	max CDATA #IMPLIED
>
<!ELEMENT intensity EMPTY>
<!ATTLIST intensity
	min CDATA #IMPLIED
	max CDATA #IMPLIED
>
<!ELEMENT desciption EMPTY>
<!ATTLIST desciption
	comment CDATA #IMPLIED
	author CDATA #IMPLIED
>
<!ELEMENT face (fap+)>
<!ELEMENT fap EMPTY>
<!ATTLIST fap
	num CDATA #IMPLIED
	value CDATA #IMPLIED
>
<!ELEMENT cons (#PCDATA)>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/r_low_tensed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="low_tensed">
	<char>
		<emotion name="tensed"/>
		<profile name="tensed"/>
		<time min="0.5" max="4"/>
		<intensity min="0.25" max="0.5"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="3" value="-89"/>
<fap num="6" value="14"/>
<fap num="7" value="14"/>
<fap num="10" value="50"/>
<fap num="11" value="50"/>
<fap num="39" value="-126"/>
<fap num="40" value="-126"/>
<fap num="51" value="148"/>
<fap num="52" value="178"/>
<fap num="53" value="9"/>
<fap num="54" value="9"/>
<fap num="55" value="89"/>
<fap num="56" value="89"/>
<fap num="57" value="15"/>
<fap num="58" value="15"/>
<fap num="59" value="-45"/>
<fap num="60" value="-45"/>
	</face>
	<cons>
	</cons>
</expression>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/high_relief.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE expression SYSTEM "./dtd/expression.dtd">

<expression name="high_relief">
	<char>
		<emotion name="relief"/>
		<profile name="relief"/>
		<time min="0.5" max="4"/>
		<intensity min="0.5" max="1"/>
		<desciption comment="" author="radek"/>
	</char>
	<face>
<fap num="3" value="40"/>
<fap num="4" value="-60"/>
<fap num="5" value="40"/>
<fap num="10" value="-120"/>
<fap num="11" value="-120"/>
<fap num="14" value="-50"/>
<fap num="15" value="-80"/>
<fap num="16" value="290"/>
<fap num="17" value="-340"/>
<fap num="39" value="20"/>
<fap num="40" value="20"/>
<fap num="41" value="90"/>
<fap num="42" value="90"/>
<fap num="51" value="30"/>
<fap num="52" value="-90"/>
<fap num="53" value="70"/>
<fap num="54" value="70"/>
<fap num="55" value="30"/>
<fap num="56" value="30"/>
<fap num="57" value="440"/>
<fap num="58" value="470"/>
<fap num="59" value="120"/>
<fap num="60" value="120"/>
<fap num="19" value="40"/>
<fap num="20" value="40"/>
<fap num="21" value="40"/>
<fap num="22" value="40"/>
<fap num="31" value="40"/>
<fap num="32" value="40"/>
<fap num="33" value="80"/>
<fap num="34" value="80"/>
<fap num="35" value="40"/>
<fap num="36" value="40"/>
	</face>
	<cons>
	</cons>
</expression>
