=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/mmsystem/xsd/behaviorsets.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

<xs:include schemaLocation="global.xsd"/>

<xs:element name="behaviorsets" type="behaviorsetsType">
</xs:element>

<xs:complexType name="behaviorsetsType">
	<xs:sequence>
		<xs:element name="behaviorset" type="behaviorsetType" minOccurs="1" maxOccurs="unbounded">
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="behaviorsetType">
	<xs:sequence>
		<xs:element name="signals" type="signalsType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="constraints" type="constraintsType" minOccurs="1" maxOccurs="1"/>	
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="constraintsType">
	<xs:sequence>
		<xs:element name="core" type="coreType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="rules" type="rulesType" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="coreType">
	<xs:sequence>
		<xs:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="implicationType">
	<xs:sequence>
		<xs:element name="ifpresent" type="itemType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="thenpresent" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="thennotpresent" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="rulesType">
	<xs:sequence>
		<xs:element name="implication" type="implicationType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="signalsType">
	<xs:sequence>
		<xs:element name="signal" type="signalType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="itemType">
	<xs:attribute name="id" type="xs:integer" use="required"/>
</xs:complexType>

<xs:complexType name="signalType">
	<xs:sequence>
		<xs:element name="alternative" type="alternativeShapeType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="id" type="xs:integer" use="required"/>
	<xs:attribute name="name" type="xs:string"/>
	<xs:attribute name="modality" type="parametersetNameType" use="required"/>
</xs:complexType>

<xs:complexType name="alternativeShapeType">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="probability" type="xs:decimal" use="required"/>
</xs:complexType>



</xs:schema>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/mmsystem/lexicon.xml
<?xml version="1.0"?>

<behaviorsets
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="behaviorsets.xsd">

	<behaviorset name="other-head_left">
		<signals>
			<signal id="1" name="head_left" modality="head"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="other-head_right">
		<signals>
			<signal id="1" name="head_right" modality="head"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="other-culture">
		<signals>
			<signal id="1" name="ADJECTIVAL=culture3" modality="gesture"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="world-object-shape">
		<signals>
			<signal id="1" name="deictic=view3" modality="gesture"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="world-object-quantity">
		<signals>
			<signal id="1" name="adjectival=many" modality="gesture"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="world-object-location">
		<signals>
			<signal id="1" name="adjectival=wipe" modality="gesture"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

<behaviorset name="world-place-location">
		<signals>
			<signal id="1" name="adjectival=upright" modality="gesture"/>
		</signals>
		<constraints>
			<core>				
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="belief-relation-metaphoric">
		<signals>
			<signal id="1" name="ADJECTIVAL=METAPHORIC2" modality="gesture"/>
		</signals>
		<constraints>
			<core>
				<item id="1"/>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="performative-deny">
		<signals>
			<signal id="1" name="shake" modality="head">
				<alternative name="up" probability="0.5"/>
			</signal>
			<signal id="2" name="certainty=dont_know" modality="gesture"/>
			<signal id="3" name="eyes=close" modality="gaze"/>
			<signal id="4" name="eyes=frown" modality="face"/>
		</signals>
		<constraints>
			<core>
				<item id="2"/>
			</core>
			<rules>
				<implication>
					<ifpresent id="2"/>
					<thenpresent id="3"/>
				</implication>
				<implication>
					<ifpresent id="3"/>
					<thenpresent id="2"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>

	
	<behaviorset name="performative-greet">
		<signals>
			<signal id="1" name="performative=greet" modality="face"/>
			<signal id="2" name="adjectival=hello" modality="gesture"/>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
			<signal id="4" name="nod" modality="head"/>
			<signal id="5" name="bow" modality="torso"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
				<implication>
					<ifpresent id="5"/>
					<thenpresent id="4"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="performative-inform">
		<signals>
			<signal id="1" name="performative=inform" modality="face"/>
			<signal id="2" name="adjectival=SHOW_LHAND" modality="gesture"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="performative-propose">
		<signals>
			<signal id="1" name="performative=propose" modality="face"/>
			<signal id="2" name="adjectival=OPEN_MOVING_HAND" modality="gesture"/>
			<signal id="3" name="nod" modality="head"/>
			<signal id="4" name="anger" modality="torso"/>
			<signal id="5" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="performative-suggest">
		<signals>
			<signal id="1" name="performative=suggest" modality="face"/>
			<signal id="2" name="adjectival=WARNING_HAND" modality="gesture"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="performative-warn">
		<signals>
			<signal id="1" name="performative=warn" modality="face"/>
			<signal id="2" name="adjectival=WARNING_HAND" modality="gesture"/>
			<signal id="3" name="nod" modality="head"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="certainty-certain">
		<signals>
			<signal id="1" name="nod" modality="head"/>
			<signal id="2" name="ADJECTIVAL=SHOW_LHAND" modality="gesture"/>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
			<signal id="4" name="certainty=certain" modality="face"/>
		</signals>
		<constraints>
		</constraints>
	</behaviorset>
	
	<behaviorset name="turntaking-takethefloor">
		<signals>
			<signal id="1" name="turnallocation=take" modality="face"/>
			<signal id="2" name="raise" modality="torso"/>
		</signals>
		<constraints>
		</constraints>
	</behaviorset>
	
	<behaviorset name="turntaking-givethefloor">
		<signals>
			<signal id="1" name="turnallocation=give" modality="face"/>
			<signal id="2" name="raise" modality="torso"/>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
			<signal id="3" name="adjectival=OPEN_MOVING_HAND2" modality="gesture"/>
		</signals>
		<constraints>
			<core>
				<item id="3"/>
			</core>
		</constraints>
	</behaviorset>
	
	<behaviorset name="turntaking-*">
		<signals>
			<signal id="1" name="nod" modality="head"/>
			<signal id="2" name="gaze=look_at" modality="gaze"/>
			<signal id="3" name="eyes=raise_eyebrows" modality="face"/>
		</signals>
		<constraints>
			<rules>
				<implication>
					<ifpresent id="1"/>
					<thennotpresent id="2"/>
					<thennotpresent id="3"/>
				</implication>
				<implication>
					<ifpresent id="2"/>
					<thennotpresent id="1"/>
					<thennotpresent id="3"/>
				</implication>
				<implication>
					<ifpresent id="3"/>
					<thennotpresent id="1"/>
					<thennotpresent id="2"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="belief-relation-enumerate">
		<signals>
			<signal id="1" name="nod" modality="head"/>
			<signal id="2" name="ADJECTIVAL=WARNING_HAND" modality="gesture"/>
		</signals>
		<constraints>
		</constraints>
	</behaviorset>
	<behaviorset name="belief-relation-enumerate1">
		<signals>

			<signal id="1" name="ADJECTIVAL=one" modality="gesture"/>
		</signals>
		<constraints>
		</constraints>
	</behaviorset>
	<behaviorset name="belief-relation-enumerate2">
		<signals>

			<signal id="1" name="ADJECTIVAL=two" modality="gesture"/>
		</signals>
		<constraints>
		</constraints>
	</behaviorset>
	<behaviorset name="belief-relation-enumerate3">
		<signals>

			<signal id="1" name="ADJECTIVAL=three" modality="gesture"/>
		</signals>
		<constraints>
		</constraints>
	</behaviorset>
	
	<behaviorset name="emotion-sadness">
		<signals>
			<signal id="1" name="down" modality="head"/>
			<signal id="2" name="adjectival=dispersed" modality="gesture"/>
			<signal id="3" name="gaze=look_down" modality="gaze"/>
			<signal id="4" name="affect=sadness" modality="face"/>
		</signals>
		<constraints>
			<core>
				<item id="4"/>
			</core>
			<rules>
				<implication>
					<ifpresent id="2"/>
					<thenpresent id="3"/>
				</implication>
				<implication>
					<ifpresent id="3"/>
					<thenpresent id="2"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="emotion-despair">
		<signals>
			<signal id="1" name="down" modality="head"/>
			<signal id="2" name="gaze=look_down" modality="gaze"/>
			<signal id="3" name="affect=despair" modality="face"/>
		</signals>
		<constraints>
			<core>
				<item id="3"/>
			</core>
			<rules>
				<implication>
					<ifpresent id="1"/>
					<thenpresent id="2"/>
				</implication>
				<implication>
					<ifpresent id="2"/>
					<thenpresent id="1"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>


	<behaviorset name="emotion-small_sadness">
		<signals>
			<signal id="1" name="affect=small_sadness" modality="face"/>
			<signal id="2" name="head=head_down" modality="head"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="emotion-anger">
		<signals>
			<signal id="1" name="look_at" modality="head"/>
			<signal id="2" modality="gesture"  name="emotion=anger"/>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
			<signal id="4" name="affect=anger" modality="face"/>
			<signal id="5" name="anger" modality="torso"/>
		</signals>
		<constraints>
			<core>
				<item id="4"/>
			</core>
			<rules>
				<implication>
					<ifpresent id="3"/>
					<thenpresent id="1"/>
				</implication>
				<implication>
					<ifpresent id="5"/>
					<thenpresent id="2"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>

	<behaviorset name="emotion-small_anger">
		<signals>
			<signal id="1" name="affect=small_anger" modality="face"/>
		</signals>
		<constraints>
			<core>
			</core>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="emotion-joy">
		<signals>
			<signal id="1" name="look_at" modality="head"/>
			<signal id="3" name="affect=joy" modality="face"/>
			<signal id="4" name="raise" modality="torso"/>
		</signals>
