=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/mmsystem/xsd/profiles.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

<xs:include schemaLocation="global.xsd"/>

<xs:complexType name="parameterType">
	<xs:attribute name="name" type="parameterNameType" use="required"/>
	<xs:attribute name="value" type="xs:decimal" use="required"/>
</xs:complexType>
		
<xs:complexType name="parsetType">
	<xs:sequence>
		<xs:element name="Parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="parametersetNameType" use="required"/>
</xs:complexType>

<xs:complexType name="parsetsType">
	<xs:sequence>
		<xs:element name="parameter-set" type="parsetType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="profile" type="parsetsType">
</xs:element>

</xs:schema>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/listenerbl.xml
<?xml version="1.0"?>

<profile
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="profiles.xsd">


	<modality name="face">
		<Parameter name="preference.value" value="0.9"/><Parameter name="preference.min" value="0.0"/><Parameter name="preference.max" value="1.0"/>
		<Parameter name="OAC.value" value="0.95"/><Parameter name="OAC.min" value="0"/><Parameter name="OAC.max" value="1.0"/>
		<Parameter name="SPC.value" value="0.0"/><Parameter name="SPC.min" value="-1.0"/><Parameter name="SPC.max" value="1.0"/>
		<Parameter name="TMP.value" value="0.05"/><Parameter name="TMP.min" value="-1.0"/><Parameter name="TMP.max" value="1.0"/>
		<Parameter name="FLD.value" value="-0.05"/><Parameter name="FLD.min" value="-1.0"/><Parameter name="FLD.max" value="1.0"/>
		<Parameter name="PWR.value" value="0.1"/><Parameter name="PWR.min" value="-1.0"/><Parameter name="PWR.max" value="1.0"/>
		<Parameter name="REP.value" value="-0.1"/><Parameter name="REP.min" value="-1.0"/><Parameter name="REP.max" value="1.0"/>
	</modality>
	<modality name="gesture">
		<Parameter name="preference.value" value="0.2"/><Parameter name="preference.min" value="0.0"/><Parameter name="preference.max" value="1.0"/>
		<Parameter name="OAC.value" value="0.25"/><Parameter name="OAC.min" value="0"/><Parameter name="OAC.max" value="1.0"/>
		<Parameter name="SPC.value" value="0.00"/><Parameter name="SPC.min" value="-1.0"/><Parameter name="SPC.max" value="1.0"/>
		<Parameter name="TMP.value" value="0.05"/><Parameter name="TMP.min" value="-1.0"/><Parameter name="TMP.max" value="1.0"/>
		<Parameter name="FLD.value" value="-0.05"/><Parameter name="FLD.min" value="-1.0"/><Parameter name="FLD.max" value="1.0"/>
		<Parameter name="PWR.value" value="0.1"/><Parameter name="PWR.min" value="-1.0"/><Parameter name="PWR.max" value="1.0"/>
		<Parameter name="REP.value" value="-0.1"/><Parameter name="REP.min" value="-1.0"/><Parameter name="REP.max" value="1.0"/>
	</modality>

	<modality name="gaze">
		<Parameter name="lookat.value" value="0"/>
		<Parameter name="rotation.x" value="0.0"/>
		<Parameter name="rotation.y" value="0.0"/>
		<Parameter name="rotation.z" value="0.0"/>
		<Parameter name="preference.value" value="0.9"/><Parameter name="preference.min" value="0.0"/><Parameter name="preference.max" value="1.0"/>
		<Parameter name="OAC.value" value="0.95"/><Parameter name="OAC.min" value="0"/><Parameter name="OAC.max" value="1.0"/>
		<Parameter name="SPC.value" value="0.0"/><Parameter name="SPC.min" value="-1.0"/><Parameter name="SPC.max" value="1.0"/>
		<Parameter name="TMP.value" value="0.05"/><Parameter name="TMP.min" value="-1.0"/><Parameter name="TMP.max" value="1.0"/>
		<Parameter name="FLD.value" value="-0.05"/><Parameter name="FLD.min" value="-1.0"/><Parameter name="FLD.max" value="1.0"/>
		<Parameter name="PWR.value" value="0.1"/><Parameter name="PWR.min" value="-1.0"/><Parameter name="PWR.max" value="1.0"/>
		<Parameter name="REP.value" value="-0.1"/><Parameter name="REP.min" value="-1.0"/><Parameter name="REP.max" value="1.0"/>
	</modality>
	<modality name="torso">
		<Parameter name="preference.value" value="0.2"/><Parameter name="preference.min" value="0.0"/><Parameter name="preference.max" value="1.0"/>
		<Parameter name="OAC.value" value="0.25"/><Parameter name="OAC.min" value="0"/><Parameter name="OAC.max" value="1.0"/>
		<Parameter name="SPC.value" value="0.00"/><Parameter name="SPC.min" value="-1.0"/><Parameter name="SPC.max" value="1.0"/>
		<Parameter name="TMP.value" value="0.05"/><Parameter name="TMP.min" value="-1.0"/><Parameter name="TMP.max" value="1.0"/>
		<Parameter name="FLD.value" value="-0.05"/><Parameter name="FLD.min" value="-1.0"/><Parameter name="FLD.max" value="1.0"/>
		<Parameter name="PWR.value" value="0.1"/><Parameter name="PWR.min" value="-1.0"/><Parameter name="PWR.max" value="1.0"/>
		<Parameter name="REP.value" value="-0.1"/><Parameter name="REP.min" value="-1.0"/><Parameter name="REP.max" value="1.0"/>
	</modality>
	<modality name="head">
		<Parameter name="preference.value" value="0.9"/><Parameter name="preference.min" value="0.0"/><Parameter name="preference.max" value="1.0"/>
		<Parameter name="OAC.value" value="0.95"/><Parameter name="OAC.min" value="0"/><Parameter name="OAC.max" value="1.0"/>
		<Parameter name="SPC.value" value="0.0"/><Parameter name="SPC.min" value="-1.0"/><Parameter name="SPC.max" value="1.0"/>
		<Parameter name="TMP.value" value="0.05"/><Parameter name="TMP.min" value="-1.0"/><Parameter name="TMP.max" value="1.0"/>
		<Parameter name="FLD.value" value="-0.05"/><Parameter name="FLD.min" value="-1.0"/><Parameter name="FLD.max" value="1.0"/>
		<Parameter name="PWR.value" value="0.1"/><Parameter name="PWR.min" value="-1.0"/><Parameter name="PWR.max" value="1.0"/>
		<Parameter name="REP.value" value="-0.1"/><Parameter name="REP.min" value="-1.0"/><Parameter name="REP.max" value="1.0"/>

	</modality>
</profile>
