=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/environments/environment.dtd
<!ELEMENT ENVIRONMENT (AGENTS,OBJECTS)>

<!ELEMENT AGENTS (AGENT)*>
<!ELEMENT OBJECTS (OBJECT)*>
<!ELEMENT AGENT EMPTY>
<!ELEMENT OBJECT EMPTY>

<!ATTLIST AGENT name			CDATA	#REQUIRED>
<!ATTLIST AGENT character		CDATA	#REQUIRED>
<!ATTLIST AGENT position_x		CDATA	"0">
<!ATTLIST AGENT position_y		CDATA	"0">
<!ATTLIST AGENT position_z		CDATA	"0">
<!ATTLIST AGENT rotation_x		CDATA	"0">
<!ATTLIST AGENT rotation_y		CDATA	"0">
<!ATTLIST AGENT rotation_z		CDATA	"0">

<!ATTLIST OBJECT name			CDATA	#REQUIRED>
<!ATTLIST OBJECT object_shape		CDATA	#REQUIRED>
<!ATTLIST OBJECT position_x		CDATA	"0">
<!ATTLIST OBJECT position_y		CDATA	"0">
<!ATTLIST OBJECT position_z		CDATA	"0">
<!ATTLIST OBJECT rotation_x		CDATA	"0">
<!ATTLIST OBJECT rotation_y		CDATA	"0">
<!ATTLIST OBJECT rotation_z		CDATA	"0">

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/environments/environment1.xml
<?xml version="1.0"?>
<!DOCTYPE ENVIRONMENT SYSTEM "environment.dtd" []>
<ENVIRONMENT>
<AGENTS>
<AGENT name="greta" character="greta" position_y="90"/>
</AGENTS>
<OBJECTS>
<OBJECT name="wall1" object_shape="wall" position_x="0" position_y="0" position_z="-1000" rotation_x="90"/>
<OBJECT name="wall2" object_shape="wall" position_x="0" position_y="0" position_z="1000" rotation_x="90" rotation_z="180"/>
<OBJECT name="wall3" object_shape="wall" position_x="1000" position_y="0" position_z="0" rotation_x="90" rotation_z="-270"/>
<OBJECT name="wall4" object_shape="wall" position_x="-1000" position_y="0" position_z="0" rotation_x="90" rotation_z="-90"/>
<OBJECT name="floor" object_shape="floor" position_x="0" position_y="0" position_z="0"/>
<OBJECT name="roof" object_shape="roof" position_x="0" position_y="0" position_z="0"/>
</OBJECTS>
</ENVIRONMENT>
