=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/bml/callas/bml.dtd
<!ELEMENT bml (speech|head|face|gesture|gaze|torso)+>

<!ELEMENT speech (#PCDATA|tm|pause|pitchaccent|boundary|description)*>
<!ELEMENT head (description)?>
<!ELEMENT face (description)?>
<!ELEMENT gesture (description)?>
<!ELEMENT torso (description)?>
<!ELEMENT gaze (description)?>

<!ELEMENT tm EMPTY>

<!ELEMENT pause EMPTY>

<!ELEMENT pitchaccent EMPTY>

<!ELEMENT boundary EMPTY>

<!ELEMENT description (reference|SPC.min|SPC.max|SPC.value|TMP.min|TMP.max|TMP.value|FLD.min|FLD.max|FLD.value|PWR.min|PWR.max|PWR.value|OAC.min|OAC.max|OAC.value|REP.min|REP.max|REP.value|preference.min|preference.max|preference.value)*>

<!ELEMENT reference (#PCDATA)>

<!ELEMENT SPC.min (#PCDATA)>
<!ELEMENT SPC.max (#PCDATA)>
<!ELEMENT SPC.value (#PCDATA)>
<!ELEMENT TMP.min (#PCDATA)>
<!ELEMENT TMP.max (#PCDATA)>
<!ELEMENT TMP.value (#PCDATA)>
<!ELEMENT FLD.min (#PCDATA)>
<!ELEMENT FLD.max (#PCDATA)>
<!ELEMENT FLD.value (#PCDATA)>
<!ELEMENT PWR.min (#PCDATA)>
<!ELEMENT PWR.max (#PCDATA)>
<!ELEMENT PWR.value (#PCDATA)>
<!ELEMENT OAC.min (#PCDATA)>
<!ELEMENT OAC.max (#PCDATA)>
<!ELEMENT OAC.value (#PCDATA)>
<!ELEMENT REP.min (#PCDATA)>
<!ELEMENT REP.max (#PCDATA)>
<!ELEMENT REP.value (#PCDATA)>
<!ELEMENT preference.min (#PCDATA)>
<!ELEMENT preference.max (#PCDATA)>
<!ELEMENT preference.value (#PCDATA)>

<!ATTLIST speech id ID #REQUIRED start CDATA "0" type CDATA #IMPLIED text CDATA #IMPLIED speed_num CDATA #IMPLIED speed_sym (fast|medium|slow) "medium" language CDATA #REQUIRED voice CDATA #REQUIRED>

<!ATTLIST head id ID #REQUIRED>
<!ATTLIST head type (NOD|SHAKE|TOSS|ORIENT) "NOD">
<!ATTLIST head direction (RIGHT|LEFT|UP|DOWN|ROLLRIGHT|ROLLLEFT) "RIGHT">
<!ATTLIST head start CDATA #REQUIRED>
<!ATTLIST head stroke CDATA #IMPLIED>
<!ATTLIST head end CDATA "1">

<!ATTLIST face id ID #REQUIRED>
<!ATTLIST face type (FACS|EYEBROWS|EYELIDS|MOUTH) "MOUTH">
<!ATTLIST face au CDATA "0">
<!ATTLIST face separation CDATA "0.5">
<!ATTLIST face lid (BOTH|UPPER|LOWER) "BOTH">
<!ATTLIST face shape (POINTDOWN|POINTUP|FLAT|SMILE|LAUGH|PUCKER|FROWN) "FLAT">
<!ATTLIST face start CDATA #REQUIRED>
<!ATTLIST face stroke CDATA #IMPLIED>
<!ATTLIST face end CDATA "1">

<!ATTLIST gesture id ID #REQUIRED>
<!ATTLIST gesture type (POINT|REACH|BEAT|DEPICT|SIGNAL) "BEAT">
<!ATTLIST gesture name CDATA #IMPLIED>
<!ATTLIST gesture target CDATA #IMPLIED>
<!ATTLIST gesture start CDATA #REQUIRED>
<!ATTLIST gesture stroke CDATA #IMPLIED>
<!ATTLIST gesture end CDATA "1">

<!ATTLIST torso id ID #REQUIRED>
<!ATTLIST torso posture CDATA #REQUIRED>
<!ATTLIST torso start CDATA #REQUIRED>
<!ATTLIST torso stroke CDATA #IMPLIED>
<!ATTLIST torso end CDATA "1">

<!ATTLIST gaze id ID #REQUIRED>
<!ATTLIST gaze start CDATA #REQUIRED>
<!ATTLIST gaze stroke CDATA #IMPLIED>
<!ATTLIST gaze end CDATA "1">

<!ATTLIST tm id ID #REQUIRED>

<!ATTLIST tm time CDATA #IMPLIED>

<!ATTLIST pause id ID #REQUIRED duration_num CDATA #IMPLIED duration_sym (short|medium|long) "medium">

<!ATTLIST pitchaccent id ID #REQUIRED type (Hstar|Lstar|LplusHstar|LstarplusH|HstarplusL|HplusLstar) "Hstar" level (strong|medium|weak) "medium" start CDATA #REQUIRED end CDATA #IMPLIED activation CDATA "1">
                   
<!ATTLIST boundary id ID #REQUIRED type (L|H|LL|HH|LH|HL) "LL" start CDATA #REQUIRED end CDATA "0.5">

<!ATTLIST description level (1|2|3|4|5|6|7|8|9) #REQUIRED>
<!ATTLIST description type CDATA #REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/bml/callas/tension20.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE bml SYSTEM "bml.dtd" []>

<bml>

<!-- expression 1 -->

<face id='ex1f1' start='1.11864' end='4.05085'>
	  <description level="1" type="gretabml">
		<reference>affect=tensed1</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 2 -->

<face id='ex2f2' start='7.67796' end='3.9661'>
	  <description level="1" type="gretabml">
		<reference>affect=tensed2</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 3 -->

<face id='ex3f3' start='14.4238' end='4.20339'>
	  <description level="1" type="gretabml">
		<reference>affect=tensed3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

	<gaze id='ex3o2' start='15.0847' stroke='15.3339' end='1.0339'>
	  <description level="1" type="gretabml">
		<reference>gaze=look_right</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>0.9</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</gaze>


	<gaze id='ex3o1' stroke='16.3339' start='16.1864' end='1.01'>
	  <description level="1" type="gretabml">
		<reference>gaze=look_left</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>0.9</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</gaze>


<!-- expression 4 -->

<face id='ex4f4' start='21.2712' end='5.08473'>
	  <description level="1" type="gretabml">
		<reference>affect=tensed4</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

	<gaze id='ex4o3' stroke='22.3339' start='21.8644' end='1.61018'>
	  <description level="1" type="gretabml">
		<reference>gaze=look_right</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>0.9</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</gaze>


	<gaze id='ex4o4' stroke='34.0339' start='23.4746' end='1.61015'>
	  <description level="1" type="gretabml">
		<reference>gaze=look_down</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>0.9</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</gaze>

	<head id='ex4h1' start='21.9492' end='1.35593'>
	  <description level="1" type="gretabml">
		<reference>head=head_right</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>-0.97</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</head>

	<head id='ex4h2' start='23.3898' end='1.52546'>
	  <description level="1" type="gretabml">
		<reference>head=head_left</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>1</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</head>

<!-- expression 5 -->

	<face id='ex8f8' type='MOUTH' shape='SMILE' start='30.5017' end='6.04407'>
	  <description level="1" type="gretabml">
		<reference>affect=tensed3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>


<torso id='exp5t2' posture='extend'  start='31.9017' stroke='4.2' end='6.04407'>
	  <description level="1" type="gretabml">
		<reference>tensed</reference>
		<SPC.value>-0.5</SPC.value>
		<TMP.value>-1</TMP.value>
		<FLD.value> -1</FLD.value>
		<PWR.value>-1</PWR.value>
	  </description>
	</torso>

<!-- expression 6 -->

	<face id='ex7f7' type='MOUTH' shape='SMILE' start='43.9322' end='65.44407'>
	  <description level="1" type="gretabml">
		<reference>affect=tensed3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

	<face id='ex8f9' type='MOUTH' shape='SMILE' start='46.77' end='3'>
	  <description level="1" type="gretabml">
		<reference>certainty=eyes_closed</reference>
		<SPC.value>1</SPC.value>
		<TMP.value>0.9</TMP.value>
		<FLD.value>-1.0</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</face>

	<gesture id='ex7gesture3' type='BEAT' stroke='0.4' start='46.9017' end='2.84407'>
	  <description level="1" type="gretabml">
		<reference>EMOTION=tension21</reference>
		<SPC.value>0.1</SPC.value>
		<TMP.value>1</TMP.value>
		<FLD.value>-1</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</gesture>

<!-- expression 8 -->


</bml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/bml/callas/fear21.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE bml SYSTEM "bml.dtd" []>

<bml>

<!-- expression 1 -->

<face id='ex1' start='0.881352' end='3.62712'>
  <description level="1" type="gretabml">
		<reference>affect=fear1</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 2 -->

<face id='ex2' start='6.52542' end='4.32204'>
  <description level="1" type="gretabml">
		<reference>affect=fear2</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>


<!-- expression 3 -->

<face id='ex3' start='12.6949' end='5.0678'>
  <description level="1" type="gretabml">
		<reference>affect=fear3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 4 -->

<face id='ex4' start='19.7289' end='4.69572'>
  <description level="1" type="gretabml">
		<reference>affect=fear4</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 5 -->

	<face id='exp7f3' start='20.8439' end='3.15254'>
	  <description level="1" type="gretabml">
		<reference>affect=fear3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

	<gesture id='exp7handon' start='21.3478' stroke='0.9' end='3.85053'>
	  <description level="1" type="gretabml">
		<reference>EMOTION=FEAR22</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>1</TMP.value>
		<FLD.value>-1</FLD.value>
		<PWR.value>1</PWR.value>
	  </description>
	</gesture>

<!-- expression 6 -->

	<face id='exp8f5' start='28.0894' end='3.15254'>
	  <description level="1" type="gretabml">
		<reference>affect=fear3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

	<gesture id='exp8handface' start='28.7382' stroke='0.3' end='3.58983'>
	  <description level="1" type="gretabml">
		<reference>EMOTION=FEAR11</reference>
		<SPC.value>-0.41</SPC.value>
		<TMP.value>1</TMP.value>
		<FLD.value>-1</FLD.value>
		<PWR.value>0.99</PWR.value>
	  </description>
	</gesture>

</bml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/bml/callas/relief20.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE bml SYSTEM "bml.dtd" []>

<bml>

<!-- expression 1 -->

<face id='exp1f1' start='1.0' end='4'>
	  <description level="1" type="gretabml">
		<reference>affect=relief1</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 2 -->

<face id='exp2f2' type='MOUTH' shape='SMILE' start='5' end='4'>
	  <description level="1" type="gretabml">
		<reference>affect=relief2</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<!-- expression 3 -->

<face id='exp3f3' start='10' end='4'>
	  <description level="1" type="gretabml">
		<reference>affect=relief3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>


<!-- expression 4 -->

<face id='exp4f4' start='16.010165' end='7.07797'>
	  <description level="1" type="gretabml">
		<reference>affect=relief2</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>


<torso id='exp4t1' posture='extend' start='16.610165' stroke='4.2' end='8.67797'>
	  <description level="1" type="gretabml">
		<reference>relief4</reference>
		<SPC.value>-0.5</SPC.value>
		<TMP.value>1</TMP.value>
		<FLD.value>1.0</FLD.value>
		<PWR.value>-0.5</PWR.value>
	  </description>
	</torso>


<!-- expression 5 -->

<face id='exp5f5' start='28.610165' end='5.67797'>
	  <description level="1" type="gretabml">
		<reference>affect=relief3</reference>
		<SPC.value>0</SPC.value>
		<TMP.value>0</TMP.value>
		<FLD.value>0</FLD.value>
		<PWR.value>0</PWR.value>
	  </description>
	</face>

<torso id='exp5t2' posture='extend' start='27.610165' end='5.67797' stroke='2.2'>
	  <description level="1" type="gretabml">
		<reference>relief5</reference>
		<SPC.value>-0.5</SPC.value>
		<TMP.value>1</TMP.value>
		<FLD.value>1.0</FLD.value>
		<PWR.value>-0.1</PWR.value>
	  </description>
	</torso>

</bml>
