=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/RulesGreta2/rules.dtd
<!ELEMENT rules (rule*)>
	
<!ELEMENT rule (parameter*)>
<!ATTLIST rule
	name CDATA #REQUIRED>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/RulesGreta2/rules.xml
<?xml version="1.0"?>
<!DOCTYPE rules SYSTEM "rules.dtd" []>

<rules>
	<rule name="head_nod">
		<parameter name="modality" value="head" />
		<parameter name="priority" value="3" />
		<parameter name="probability" value="1.0" />
	</rule>

	<rule name="head_shake">
		<parameter name="modality" value="head" />
		<parameter name="priority" value="1" />
		<parameter name="probability" value="1.0" />
	</rule>

	<rule name="POSES">
		<parameter name="modality" value="head" />
		<parameter name="priority" value="2" />
		<parameter name="probability" value="1.0" />
	</rule>

	<rule name="mouth=smile">
		<parameter name="modality" value="face" />
		<parameter name="priority" value="1" />
		<parameter name="probability" value="0.8" />
	</rule>


	<rule name="PITCH">
		<parameter name="modality" value="speech" />
		<parameter name="priority" value="2" />
		<parameter name="probability" value="0.7" />
	</rule>
	
</rules>
