=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/RulesGreta2/rulesfile.dtd
<!ELEMENT rules (rule+)>
	
<!ELEMENT rule (usersignals,constraints?,response)>
<!ATTLIST rule
	name CDATA #REQUIRED>

<!ELEMENT usersignals (usersignal+)>

<!ELEMENT usersignal EMPTY>
<!ATTLIST usersignal
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	modality CDATA #REQUIRED>

<!ELEMENT constraints (core?,implications?)>

<!ELEMENT core (item+)>

<!ELEMENT item EMPTY>
<!ATTLIST item
	id CDATA #REQUIRED>

<!ELEMENT implications (implication+)>

<!ELEMENT implication (ifpresent,thenpresent)>

<!ELEMENT ifpresent EMPTY>
<!ATTLIST ifpresent
	id CDATA #REQUIRED>

<!ELEMENT thenpresent EMPTY>
<!ATTLIST thenpresent
	id CDATA #REQUIRED>

<!ELEMENT response (signals?,cognitive?)>
<!ATTLIST response
	probability CDATA #REQUIRED
	priority CDATA #REQUIRED>

<!ELEMENT signals (signal+)>
<!ATTLIST signals
	probability CDATA #REQUIRED>

<!ELEMENT signal EMPTY>
<!ATTLIST signal
	name CDATA #REQUIRED
	modality CDATA #REQUIRED>

<!ELEMENT cognitive EMPTY>
<!ATTLIST cognitive
	probability CDATA #REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/listener/RulesGreta2/rulesfile.xml
<?xml version="1.0"?>
<!DOCTYPE rules SYSTEM "rulesfile.dtd" []>

<rules>
	<rule name="trigger-head_nod">

		<usersignals>
			<usersignal id="1" name="head_nod" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="2">
			<signals probability="0.6">
				<signal name="head=head_nod" modality="head"/>
			</signals>
			
			<cognitive probability="0.4"/>
		</response>
	</rule>

	<rule name="trigger-head_nod_fast">

		<usersignals>
			<usersignal id="1" name="head_nod_fast" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="2">
			<signals probability="0.6">
				<signal name="head=head_nod2" modality="head"/>
			</signals>
			
			<cognitive probability="0.4"/>
		</response>
	</rule>

	<rule name="trigger-head_nod_slow">

		<usersignals>
			<usersignal id="1" name="head_nod_slow" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="2">
			<signals probability="0.6">
				<signal name="head=head_nod1" modality="head"/>
			</signals>
			
			<cognitive probability="0.4"/>
		</response>
	</rule>

	<rule name="trigger-head_shake">

		<usersignals>
			<usersignal id="1" name="head_shake" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="2">
			<signals probability="0.6">
				<signal name="head=head_shake" modality="head"/>
			</signals>
			
			<cognitive probability="0.4"/>
		</response>
	</rule>

	<rule name="trigger-head_infront">

		<usersignals>
			<usersignal id="1" name="head_infront" modality="head"/>
		</usersignals>

		<response probability="1.0" priority="1">
			
			<cognitive probability="1.0"/>
		</response>
	</rule>

	<rule name="trigger-head_up">

		<usersignals>
			<usersignal id="1" name="head_up" modality="head"/>
		</usersignals>

		<response probability="1.0" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down">

		<usersignals>
			<usersignal id="1" name="head_down" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_right">

		<usersignals>
			<usersignal id="1" name="head_right" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_right" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_left">

		<usersignals>
			<usersignal id="1" name="head_left" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_left" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_right">

		<usersignals>
			<usersignal id="1" name="head_up_right" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_right" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_left">

		<usersignals>
			<usersignal id="1" name="head_up_left" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_left" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down_right">

		<usersignals>
			<usersignal id="1" name="head_down_right" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down_right" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down_left">

		<usersignals>
			<usersignal id="1" name="head_down_left" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down_left" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_aside_r">

		<usersignals>
			<usersignal id="1" name="head_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_aside_l">

		<usersignals>
			<usersignal id="1" name="head_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_aside_r">

		<usersignals>
			<usersignal id="1" name="head_up_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_aside_l">

		<usersignals>
			<usersignal id="1" name="head_up_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down_aside_r">

		<usersignals>
			<usersignal id="1" name="head_down_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down_aside_l">

		<usersignals>
			<usersignal id="1" name="head_down_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_right_aside_r">

		<usersignals>
			<usersignal id="1" name="head_right_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_right_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_right_aside_l">

		<usersignals>
			<usersignal id="1" name="head_right_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head_right_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_left_aside_r">

		<usersignals>
			<usersignal id="1" name="head_left_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_left_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_left_aside_l">

		<usersignals>
			<usersignal id="1" name="head_left_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_left_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_right_aside_r">

		<usersignals>
			<usersignal id="1" name="head_up_right_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_right_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_right_aside_l">

		<usersignals>
			<usersignal id="1" name="head_up_right_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_right_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down_right_aside_r">

		<usersignals>
			<usersignal id="1" name="head_down_right_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down_right_aside_r" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_down_right_aside_l">

		<usersignals>
			<usersignal id="1" name="head_down_right_aside_l" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_down_right_aside_l" modality="head"/>
			</signals>
			
			<cognitive probability="0.3"/>
		</response>
	</rule>

	<rule name="trigger-head_up_left_aside_r">

		<usersignals>
			<usersignal id="1" name="head_up_left_aside_r" modality="head"/>
		</usersignals>

		<response probability="0.8" priority="1">
			<signals probability="0.7">
				<signal name="head=head_up_left_aside_r" modality="head"/>
			</signals>
