=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/head/gestuary.dtd
<!ELEMENT gestuary (entry*)>

<!ELEMENT entry (verbatim,form)>
<!ELEMENT verbatim (#PCDATA)>
<!ELEMENT form (head)>
<!ELEMENT head (movement+)>
<!ELEMENT movement (timing,point+)>
<!ELEMENT timing EMPTY>
<!ELEMENT point EMPTY>

<!ATTLIST entry id CDATA #REQUIRED>
<!ATTLIST movement trajectory (linear|curved|circular) "linear">
<!ATTLIST movement phase (all_length|preparation|stroke|hold|retraction) #REQUIRED>
<!ATTLIST timing min CDATA "0">
<!ATTLIST timing max CDATA "1">
<!ATTLIST timing duration CDATA "0.3">
<!ATTLIST timing fixed (0|1) "0">
<!ATTLIST point x CDATA "0">
<!ATTLIST point y CDATA "0">
<!ATTLIST point z CDATA "0">
<!ATTLIST point spatial_fixed (0|1) "0">
<!ATTLIST point scaling CDATA "1">

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/head/gestuary.xml
<?xml version="1.0"?>
<!DOCTYPE gestuary SYSTEM "gestuary.dtd" []>

<gestuary>

	<entry id="shake">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="-10" y="0" z="0"/>
					<point x="10" y="0" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="nod">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="0" y="5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="up">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="0" y="-5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>
	
	<entry id="down">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="0" y="5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>
	
	<entry id="right">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="-10" y="0" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="left">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="10" y="0" z="0"/>
				</movement>
			</head>
		</form>
	</entry>
	
	<entry id="up_left">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="10" y="-5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="up_right">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="-10" y="-5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="down_left">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="10" y="5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="down_right">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="-10" y="5" z="0"/>
				</movement>
			</head>
		</form>
	</entry>
	
	<entry id="down_aside_right">
		<verbatim>
		</verbatim>
		<form>
			<head>
				
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="4" fixed="0"/>
					<point x="0" y="4" z="2"/>
				</movement>
			</head>
		</form>
	</entry>

	<entry id="down_aside_left">
		<verbatim>
		</verbatim>
		<form>
			<head>
				
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="0" y="4" z="-2"/>
				</movement>
			</head>
		</form>
	</entry>


	<entry id="look_at">
		<verbatim>
		</verbatim>
		<form>
			<head>
				<movement phase="stroke" trajectory="linear">
					<timing min="1" max="3" fixed="0"/>
					<point x="0" y="0" z="0"/>
				</movement>
			</head>
		</form>
	</entry>

</gestuary>
