=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/characters/dtds/character.dtd
<!ELEMENT CHARACTER (HEADFILES,BODYFILES,HEADPOSITION,LEFT_EYE,RIGHT_EYE,EYE_SCALE,TEETHS-TONGUE,HAIRPOSITION?)>

<!ELEMENT HEADFILES EMPTY>
<!ELEMENT BODYFILES EMPTY>
<!ELEMENT HEADPOSITION EMPTY>
<!ELEMENT LEFT_EYE EMPTY>
<!ELEMENT RIGHT_EYE EMPTY>
<!ELEMENT EYE_SCALE EMPTY>
<!ELEMENT TEETHS-TONGUE EMPTY>
<!ELEMENT HAIRPOSITION EMPTY>

<!ATTLIST HEADFILES vertices		CDATA	#REQUIRED>
<!ATTLIST HEADFILES fdps		CDATA	#REQUIRED>
<!ATTLIST HEADFILES indices		CDATA	#REQUIRED>
<!ATTLIST HEADFILES textured		CDATA	"0">
<!ATTLIST HEADFILES hair		CDATA	"">
<!ATTLIST HEADFILES texture_file	CDATA	"">
<!ATTLIST HEADFILES lips_texture	CDATA	"">
<!ATTLIST HEADFILES eyes_texture	CDATA	"">
<!ATTLIST BODYFILES mesh		CDATA	#REQUIRED>
<!ATTLIST BODYFILES hierarchy		CDATA	#REQUIRED>
<!ATTLIST BODYFILES bones		CDATA	#REQUIRED>
<!ATTLIST BODYFILES texture_file	CDATA	"">
<!ATTLIST LEFT_EYE x			CDATA	#REQUIRED>
<!ATTLIST LEFT_EYE y			CDATA	#REQUIRED>
<!ATTLIST LEFT_EYE z			CDATA	#REQUIRED>
<!ATTLIST RIGHT_EYE x			CDATA	#REQUIRED>
<!ATTLIST RIGHT_EYE y			CDATA	#REQUIRED>
<!ATTLIST RIGHT_EYE z			CDATA	#REQUIRED>
<!ATTLIST EYE_SCALE	factor		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE x		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE y		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE z		CDATA	#REQUIRED>
<!ATTLIST HEADPOSITION	scale		CDATA	#REQUIRED>
<!ATTLIST HEADPOSITION x		CDATA	#REQUIRED>
<!ATTLIST HEADPOSITION y		CDATA	#REQUIRED>
<!ATTLIST HEADPOSITION z		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION	scalex		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION	scaley		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION	scalez		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION x		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION y		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION z		CDATA	#REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/characters/sinkman.xml
<?xml version="1.0"?>
<!DOCTYPE CHARACTER SYSTEM "dtds/character.dtd" []>
<CHARACTER>
<HEADFILES vertices="heads/vertices/sinkman_vertices.vtx" fdps="heads/vertices/sinkman_FDPs.txt" indices="heads/vertices/sinkman_indices.txt" textured="1"
texture_file="textures/head_skin_man.bmp" eyes_texture="textures/eyes2.bmp"/>
<BODYFILES mesh="bodies/meshes/body_geometry_man.txt" hierarchy="bodies/hierarchies/hanim_hierarchy.txt" bones="bodies/bones/local_translations_man.txt" texture_file="textures/body_materials2.bmp"/>
<HEADPOSITION x="0" y="14" z="-9" scale="0.46"/>
<LEFT_EYE x="7" y="0" z="15.8"/>
<RIGHT_EYE x="-7" y="0" z="15.8"/>
<EYE_SCALE factor="2.75"/>
<TEETHS-TONGUE x="0.2" y="-2.1" z="4.9"/>
</CHARACTER>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/characters/greta.xml
<?xml version="1.0"?>
<!DOCTYPE CHARACTER SYSTEM "dtds/character.dtd" []>
<CHARACTER>
<HEADFILES vertices="heads/vertices/greta_vertices.vtx" fdps="heads/vertices/greta_FDPs.txt" indices="heads/vertices/greta_indices.txt" hair="heads/hairs/greta_hair.xml" lips_texture="textures/lips.bmp"
eyes_texture="textures/eyes.bmp"/>
<BODYFILES mesh="bodies/meshes/body_geometry_woman.txt" hierarchy="bodies/hierarchies/hanim_hierarchy.txt" bones="bodies/bones/local_translations_woman.txt" texture_file="textures/body_materials1.bmp" />
<HEADPOSITION x="0" y="24" z="0" scale="0.5116"/>
<LEFT_EYE x="7.6" y="0" z="12"/>
<RIGHT_EYE x="-7.6" y="0" z="12"/>
<EYE_SCALE factor="2.75"/>
<TEETHS-TONGUE x="0" y="-0.3" z="0.4"/>
</CHARACTER>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/characters/test.xml
<?xml version="1.0"?>
<!DOCTYPE CHARACTER SYSTEM "dtds/character.dtd" []>
<CHARACTER>
<HEADFILES vertices="heads/vertices/test.vtx" fdps="heads/vertices/sinkman_FDPs.txt" indices="heads/vertices/sinkman_indices.txt" textured="0"/>
<BODYFILES mesh="bodies/meshes/body_geometry_man.txt" hierarchy="bodies/hierarchies/hanim_hierarchy.txt" bones="bodies/bones/local_translations_man.txt" texture_file="textures/body_materials2.bmp"/>
<HEADPOSITION x="0" y="14" z="-9" scale="0.46"/>
<LEFT_EYE x="7.3" y="-0.1" z="15.3"/>
<RIGHT_EYE x="-7.3" y="-0.1" z="15.3"/>
<EYE_SCALE factor="2.55"/>
<TEETHS-TONGUE x="0.2" y="-1" z="4.9"/>
</CHARACTER>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/characters/girl.xml
<?xml version="1.0"?>
<!DOCTYPE CHARACTER SYSTEM "dtds/character.dtd" []>
<CHARACTER>
<HEADFILES vertices="heads/vertices/girl_vertices.vtx" fdps="heads/vertices/girl_FDPs.txt" indices="heads/vertices/girl_indices.txt" textured="1"
 texture_file="textures/head_skin_woman.bmp" eyes_texture="textures/eyes2.bmp"/>
<BODYFILES mesh="bodies/meshes/body_geometry_woman.txt" hierarchy="bodies/hierarchies/hanim_hierarchy.txt" bones="bodies/bones/local_translations_woman.txt" texture_file="textures/body_materials1.bmp"/>
<HEADPOSITION x="0" y="21" z="-4" scale="0.48"/>
<LEFT_EYE x="6.9" y="0" z="14.8"/>
<RIGHT_EYE x="-6.9" y="0" z="14.8"/>
<EYE_SCALE factor="2.45"/>
<TEETHS-TONGUE x="0" y="0.4" z="3.6"/>
</CHARACTER>
