=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/apml.dtd
<!ELEMENT apml (turnallocation?, performative+, turnallocation?)>

<!ATTLIST apml xml:lang CDATA "en">

<!ELEMENT turnallocation (performative)>
<!ATTLIST turnallocation type (take|give) #REQUIRED>

<!ELEMENT performative (theme|rheme)+>
<!ATTLIST performative 
type (implore|order|suggest|propose|warn|approve|praise|recognize|disagree|
agree|criticize|accept|advice|confirm|incite|refuse|question|ask|inform|request|
announce|beg|greet|paraphrase|none) #REQUIRED
		activation CDATA "1"
		>

<!ELEMENT theme (#PCDATA|emphasis|boundary|backchannel)*>
<!ATTLIST theme affect 
(anger|disgust|joy|distress|fear|sadness|surprise|embarrassment|happy-for|gloating|
resentment|relief|jealousy|envy|sorry-for|hope|satisfaction|fear-confirmed|disappointment|
pride|shame|reproach|liking|disliking|gratitude|gratification|remorse|love|hate|worried) #IMPLIED
                belief-relation
(gen-spec|cause-effect|solutionhood|suggestion|modifier|justification|contrast) #IMPLIED
                certainty 
(certain|uncertain|certainly_not|doubt) #IMPLIED
                meta-cognitive
(planning|thinking|remembering) #IMPLIED
		activation CDATA "1"
		intensity CDATA "1"
		> 

<!ELEMENT rheme (#PCDATA|emphasis|boundary|backchannel)*>
<!ATTLIST rheme affect (anger|disgust|joy|distress|fear|sadness|surprise|embarrassment|happy-for|gloating|
resentment|relief|jealousy|envy|sorry-for|hope|satisfaction|fear-confirmed|disappointment|
pride|shame|reproach|liking|disliking|gratitude|gratification|remorse|love|hate) #IMPLIED
                belief-relation
(gen-spec|cause-effect|solutionhood|suggestion|modifier|justification|contrast) #IMPLIED
                certainty 
(certain|uncertain|certainly_not) #IMPLIED
                meta-cognitive
(planning|thinking|remembering) #IMPLIED
		activation CDATA "1"
		intensity CDATA "1"
		> 

<!ELEMENT emphasis (#PCDATA)>
<!ATTLIST emphasis type (theme|rheme) #IMPLIED
                   level (strong|medium|weak) "medium"
                   x-pitchaccent (Hstar|Lstar|LplusHstar|LstarplusH|HstarplusL|HplusLstar) "Hstar"
                   deictic CDATA #IMPLIED
                   adjectival (small|subtle|tiny|difficult|big|long|large|great) #IMPLIED
				   activation CDATA "1"
		   >

<!ELEMENT boundary EMPTY>
<!ATTLIST boundary type (L|H|LL|HH|LH|HL) "LL">


<!ELEMENT backchannel EMPTY>
<!ATTLIST backchannel attitude (belief|disbelief|agreement|disagreement|acceptance|refuse|deny|confirm|
anger|disgust|joy|distress|fear|sadness|surprise|embarrassment|happy-for|gloating|resentment|relief|
jealousy|envy|sorry-for|hope|satisfaction|disappointment|pride|shame|reproach|liking|disliking|
gratitude|gratification|remorse|love|hate) #IMPLIED
                      >

<!ELEMENT pause EMPTY>
<!ATTLIST pause sec CDATA #REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/complexemotions_test_new_expressions_apml.xml
<?xml version="1.0"?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml>
<performative>
	<rheme affect="fear">
	This is	expression <emphasis x-pitchaccent="Hstar" deictic="u">of fear. </emphasis> I am <emphasis x-pitchaccent="Hstar" deictic="u">very</emphasis> scared.<boundary type="HH"/>
	</rheme>
</performative>
<performative>
	<rheme affect="complex:fear_exaggerated">
		This is expression of <emphasis x-pitchaccent="Hstar" deictic="u">exaggerated </emphasis> fear. I am <emphasis x-pitchaccent="Hstar" deictic="u">not</emphasis> so scared as you may think I am.<boundary type="HH"/>
	</rheme>
</performative>
<performative>
	<rheme affect="complex:fear_attenuated">
	and this is expression of <emphasis x-pitchaccent="Hstar" deictic="u"> attenuated</emphasis> fear. I am <emphasis x-pitchaccent="Hstar" deictic="u"> very </emphasis> scared but I do not want you know it.<boundary type="LL"/>
	</rheme>
</performative>
<performative>
	<rheme affect="complex:fear_and_anger">
	and this is expression of <emphasis x-pitchaccent="Hstar" deictic="u"> superposition</emphasis> of fear and anger. I am <emphasis x-pitchaccent="Hstar" deictic="u"> very </emphasis> scared and I am very angry.<boundary type="HH"/>
	</rheme>
</performative>
<performative>
	<rheme affect="complex:fear_maskedby_joy">
	and this is expression of fear <emphasis x-pitchaccent="Hstar" deictic="u"> masked </emphasis> by joy. I am <emphasis x-pitchaccent="Hstar" deictic="u"> very </emphasis> scared but I prefer you think that I am happy.<boundary type="LL"/>
	</rheme>
</performative>
<performative>
	<rheme affect="complex:fear_maskedby_neutral">
	and this is expression of <emphasis x-pitchaccent="Hstar" deictic="u">inhibited </emphasis> fear. I am <emphasis x-pitchaccent="Hstar" deictic="u">very </emphasis> scared but I prefer you do not know it. <boundary type="LL"/>
	</rheme>
</performative>
<performative>
	<rheme affect="complex:neutral_maskedby_fear">
		and this is expression of <emphasis x-pitchaccent="Hstar" deictic="u"> fake </emphasis> fear. I want you think that I am very scared. <boundary type="LL"/>
	</rheme>
</performative>
</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/what.xml
<?xml version="1.0"?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml xml:lang="en">

<performative type="announce">
    <rheme>
        what are you<emphasis x-pitchaccent="Hstar" deictic="u" activation="0.4">doing</emphasis>here<boundary type="HH"/>
    </rheme>
</performative>

<performative type="warn">
    <theme>Did you
        <emphasis x-pitchaccent="Hstar" activation="0.8">pay</emphasis>
        attention to what I said or
        <emphasis x-pitchaccent="Hstar" deictic="self" activation="0.9">not</emphasis><boundary type="HH"/>
    </theme>
</performative>

<performative type="suggest">
    you should
    <rheme affect="resentment">take all of
    <emphasis x-pitchaccent="Hstar" adjectival="foreign_to_me" activation="0.9">your suff</emphasis>
    <boundary type="H"/>
    </rheme> 
</performative>

<performative type="order">
	<rheme>
    and
    <emphasis x-pitchaccent="Hstar" deictic="self2" activation="0.8">get</emphasis>
    out of 
    <emphasis x-pitchaccent="Hstar" deictic="self2" activation="0.8">this</emphasis>
    place immediately
    <boundary type="L"/>
    </rheme>
</performative>

<pause sec="2.0"/>

</apml>
