=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/apml.dtd
<!ELEMENT apml (turnallocation?, performative+, turnallocation?)>

<!ATTLIST apml xml:lang CDATA "en">

<!ELEMENT turnallocation (performative)>
<!ATTLIST turnallocation type (take|give) #REQUIRED>

<!ELEMENT performative (theme|rheme)+>
<!ATTLIST performative 
type (implore|order|suggest|propose|warn|approve|praise|recognize|disagree|
agree|criticize|accept|advice|confirm|incite|refuse|question|ask|inform|request|
announce|beg|greet|paraphrase|none) #REQUIRED
		activation CDATA "1"
		>

<!ELEMENT theme (#PCDATA|emphasis|boundary|backchannel)*>
<!ATTLIST theme affect 
(anger|disgust|joy|distress|fear|sadness|surprise|embarrassment|happy-for|gloating|
resentment|relief|jealousy|envy|sorry-for|hope|satisfaction|fear-confirmed|disappointment|
pride|shame|reproach|liking|disliking|gratitude|gratification|remorse|love|hate|worried) #IMPLIED
                belief-relation
(gen-spec|cause-effect|solutionhood|suggestion|modifier|justification|contrast) #IMPLIED
                certainty 
(certain|uncertain|certainly_not|doubt) #IMPLIED
                meta-cognitive
(planning|thinking|remembering) #IMPLIED
		activation CDATA "1"
		intensity CDATA "1"
		> 

<!ELEMENT rheme (#PCDATA|emphasis|boundary|backchannel)*>
<!ATTLIST rheme affect (anger|disgust|joy|distress|fear|sadness|surprise|embarrassment|happy-for|gloating|
resentment|relief|jealousy|envy|sorry-for|hope|satisfaction|fear-confirmed|disappointment|
pride|shame|reproach|liking|disliking|gratitude|gratification|remorse|love|hate) #IMPLIED
                belief-relation
(gen-spec|cause-effect|solutionhood|suggestion|modifier|justification|contrast) #IMPLIED
                certainty 
(certain|uncertain|certainly_not) #IMPLIED
                meta-cognitive
(planning|thinking|remembering) #IMPLIED
		activation CDATA "1"
		intensity CDATA "1"
		> 

<!ELEMENT emphasis (#PCDATA)>
<!ATTLIST emphasis type (theme|rheme) #IMPLIED
                   level (strong|medium|weak) "medium"
                   x-pitchaccent (Hstar|Lstar|LplusHstar|LstarplusH|HstarplusL|HplusLstar) "Hstar"
                   deictic CDATA #IMPLIED
                   adjectival (small|subtle|tiny|difficult|big|long|large|great) #IMPLIED
				   activation CDATA "1"
		   >

<!ELEMENT boundary EMPTY>
<!ATTLIST boundary type (L|H|LL|HH|LH|HL) "LL">


<!ELEMENT backchannel EMPTY>
<!ATTLIST backchannel attitude (belief|disbelief|agreement|disagreement|acceptance|refuse|deny|confirm|
anger|disgust|joy|distress|fear|sadness|surprise|embarrassment|happy-for|gloating|resentment|relief|
jealousy|envy|sorry-for|hope|satisfaction|disappointment|pride|shame|reproach|liking|disliking|
gratitude|gratification|remorse|love|hate) #IMPLIED
                      >

<!ELEMENT pause EMPTY>
<!ATTLIST pause sec CDATA #REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/apml_when_sorrows_come.xml
<?xml version="1.0" ?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml xml:lang="en">
<performative type="announce">
<rheme affect="sadness">
When <emphasis x-pitchaccent="Hstar"> sorrows </emphasis> come <boundary type="LH"/> 
</rheme>
<rheme affect="sadness_and_anger">
they <emphasis x-pitchaccent="Hstar"> come not </emphasis> single spies 
 but in battalions <boundary type="LH"/>
</rheme>
</performative>
</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/complexemotion.xml
<?xml version="1.0"?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml>

<performative>
<rheme affect="complex:anger_maskedby_joy">
This is the <emphasis x-pitchaccent="Hstar" deictic="u">new</emphasis>expression<boundary type="LL"/>
</rheme>
</performative>

<performative>
and this is 
<rheme affect="complex:anger_and_joy">
the<emphasis x-pitchaccent="Hstar" deictic="u">same</emphasis>expression again<boundary type="LL"/>
<pause sec="5.0"/>
</rheme>
</performative>
    

<performative>
and this is 
<rheme affect="complex:worried_maskedby_neutral">
the<emphasis x-pitchaccent="Hstar" deictic="u">same</emphasis>expression again<boundary type="LL"/>
<pause sec="5.0"/>
</rheme>

</performative>

</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/intensity_hate.xml
<?xml version="1.0" ?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml xml:lang="en">
<performative type="announce">
<rheme affect="hate" intensity="0.2">
This is <emphasis x-pitchaccent="Hstar"> moderated </emphasis> expression of hate  <boundary type="LH"/> 
</rheme>
<rheme affect="hate" intensity="1">
This is expression of <emphasis x-pitchaccent="Hstar"> a strong </emphasis> hate <boundary type="LH"/> 
</rheme>
</performative>
</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/apml_what_german.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml xml:lang="de">

<performative type="announce">
    <rheme>
        Was f&#252;r <emphasis x-pitchaccent="LplusHstar" deictic="u" intensity="0.4">dich</emphasis>geht<boundary type="LH"/>
        das betrifft <emphasis x-pitchaccent="Hstar" intensity="0.4">dich</emphasis>
    </rheme>
</performative>

<performative type="warn">
    <theme>Aber
        <emphasis x-pitchaccent="Hstar" intensity="0.2">bitte</emphasis>
		erz&#228;hl mir nicht
    </theme>
    <rheme> 
        was f&#252;r
        <emphasis x-pitchaccent="Hstar" deictic="self" intensity="0.4">mich</emphasis>funktioniert
    </rheme>
</performative>

<performative type="suggest"> 
    <rheme affect="resentment">K&#252;mmer dich gef&#228;lligst um dein 
    <emphasis x-pitchaccent="Hstar" adjectival="foreign_to_me" intensity="0.6">eigenes</emphasis>
    Leben<boundary type="L"/>
    </rheme> 
</performative>
<performative type="suggest">
    und ich k&#252;mmere mich um
    <emphasis x-pitchaccent="Hstar" deictic="self2" intensity="0.6">mein</emphasis> Leben<boundary type="L"/>
</performative>
<performative type="suggest">
    <rheme>
         dann haben wir auch keine Probleme
    </rheme>
    
</performative>

<pause sec="2.0"/>

</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/apml_italian.xml
<?xml version="1.0"?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml>
<performative type="sorry-for">
buon <emphasis x-pitchaccent="Hstar">giorno</emphasis><boundary type="HL"/>
<rheme affect="joy" intensity="1.0">
mi chiamo 
<emphasis x-pitchaccent="Hstar">greta</emphasis><boundary type="LH"/>
e sono  un agente conversazionale<boundary type="HL"/>
</rheme>
</performative>
</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/intensity_tension.xml
<?xml version="1.0" ?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml xml:lang="en">
<performative type="announce">
<rheme affect="tensed" intensity="0.2">
This is a <emphasis x-pitchaccent="Hstar"> slight </emphasis> expression of tension <boundary type="LH"/> 
</rheme>

<rheme affect="tensed" intensity="0.4">
This is a <emphasis x-pitchaccent="Hstar"> moderated </emphasis> expression of tension  <boundary type="LH"/> 
</rheme>

<rheme affect="tensed" intensity="1">
This is an expression of <emphasis x-pitchaccent="Hstar"> strong </emphasis> tension <boundary type="LH"/> 
</rheme>
</performative>
</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/intensity_disgust.xml
<?xml version="1.0" ?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml xml:lang="en">
<performative type="announce">
<rheme affect="disgust" intensity="0.2">
This is <emphasis x-pitchaccent="Hstar"> moderated </emphasis> expression of disgust <boundary type="LH"/> 
</rheme>
<rheme affect="disgust" intensity="1">
This is expression of <emphasis x-pitchaccent="Hstar"> a strong </emphasis> disgust <boundary type="LH"/> 
</rheme>
</performative>
</apml>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/apml/test_italian.xml
<?xml version="1.0"?>
<!DOCTYPE apml SYSTEM "apml.dtd" []>
<apml>
<performative type="sorry-for">
	Bienvenue sur plan resto
	<boundary type="LL"/>
	ce service vous permet de
	trouver un restaurant a paris
	<boundary type="LL"/>
	pour etre mis en relation avec lui
	<boundary type="LH"/>
	vous pouvez a tout moment passer sur votre telephone
	<boundary type="LL"/>
	pour consulter le mode d emploi general
	<boundary type="LH"/>
	cliquez
	<emphasis x-pitchaccent="Hstar">
		ici
	</emphasis>
	<boundary type="LL"/>
	si vous n etes pas un utilisateur regulier
	<boundary type="LH"/>
	<rheme affect="joy" intensity="1.0">
		cliquez
		<emphasis x-pitchaccent="Hstar">
			ici
		</emphasis>
		<boundary type="LL"/>
	</rheme>
</performative>
</apml>
