=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/bml/score.dtd
<!ELEMENT score (channel*)>

<!ELEMENT channel ((hisignal|losignal|syncsignal|phasesyncsignal)*|expressivesignal*)>
<!ATTLIST channel
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	r CDATA "255"
	g CDATA "255"
	b CDATA "255"
	y CDATA "">
	
<!ELEMENT signal (hisignal|losignal|syncsignal|phasesyncsignal)>

<!ELEMENT hisignal (phase)*>
<!ATTLIST  hisignal
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	instance CDATA #REQUIRED
	start CDATA #REQUIRED
	end CDATA #REQUIRED
>

<!ELEMENT phase EMPTY>
<!ATTLIST phase
	type CDATA #REQUIRED
	duration CDATA #REQUIRED>

<!ELEMENT losignal (item*)>
<!ATTLIST    losignal
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	instance CDATA #REQUIRED
	start CDATA #REQUIRED
	end CDATA #REQUIRED
>

<!ELEMENT syncsignal (hisignal|losignal)*>
<!ATTLIST syncsignal
	type CDATA #REQUIRED>

<!ELEMENT phasesyncsignal (hisignal+,phasetosync+)>
<!ATTLIST     phasetosync
	signal CDATA #REQUIRED
	phase CDATA #REQUIRED
>

<!ELEMENT expressivesignal (hisignal|losignal|syncsignal|phasesyncsignal)*>
<!ATTLIST    expressivesignal
	OAC CDATA ""
	SPC CDATA ""
	TMP CDATA ""
	FLD CDATA ""
	PWR CDATA ""
	REP CDATA ""
>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/bml/score.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE score SYSTEM "score.dtd" []>
<score>
<channel name='face1' type='face' r='100' g='0' b='0' y='105'>
<losignal name='expr1' class='AFFECT' instance='sadness' start='0.101692' end='4.32203'/>
</channel>
<channel name='face2' type='face' r='0' g='100' b='0' y='175'>
</channel>
<channel name='face3' type='face' r='0' g='0' b='100' y='245'>
</channel>
<channel name='gestures' type='gesture' r='100' g='100' b='0' y='315'>
<losignal name='gest1' class='PERFORMATIVE' instance='GREET' start='1.01695' end='2.66102'/>
<losignal name='gest2' class='BEAT' instance='BEAT1' start='3.74576' end='6.52542'/>
</channel>
</score>
