=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/backchannellibrary.dtd
<!ELEMENT backchannellibrary (declaration,implementation)>

<!ELEMENT declaration (variabledeclaration)*>

<!ELEMENT variabledeclaration EMPTY>
<!ATTLIST variabledeclaration name CDATA #REQUIRED type CDATA #REQUIRED>

<!ELEMENT implementation (rule)*>

<!ELEMENT rule (condition|consequence)*>
<!ATTLIST rule name CDATA #REQUIRED type CDATA #REQUIRED priority CDATA #REQUIRED> 

<!ELEMENT condition (subcondition|test|operator)*>

<!ELEMENT subcondition (subcondition|test|operator)*>

<!ELEMENT test EMPTY>
<!ATTLIST test var CDATA #REQUIRED op CDATA #REQUIRED val CDATA #REQUIRED>

<!ELEMENT consequence (subconsequence|variable|operator)*>

<!ELEMENT subconsequence (subconsequence|variable|operator)*>

<!ELEMENT operator EMPTY>
<!ATTLIST operator symbol CDATA #REQUIRED>


<!ELEMENT variable EMPTY>
<!ATTLIST variable name CDATA #REQUIRED>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/backchannellibrary.xml
<?xml version="1.0"?>
<!DOCTYPE backchannellibrary SYSTEM "backchannellibrary.dtd" []>

<backchannellibrary>

<declaration>

  <variabledeclaration name="GENERAL_BEHAVIOUR" type="string" />
  <variabledeclaration name="ATTENTION_LEVEL" type="float" />

</declaration>

<implementation>


<rule name="MIX" type="activation" priority="2">

  <condition>
      <test var="state" op="==" val="1"/>
      <operator symbol="or"/>
      <test var="state" op="==" val="-1"/>
      <operator symbol="or"/>
      <subcondition>
        <test var="Hx.motionless" op="more" val="2" />
        <operator symbol="and"/>
        <test var="Hy.motionless" op="more" val="2" />
        <operator symbol="and"/>
        <test var="Hz.motionless" op="more" val="2" />
      </subcondition>
  </condition>


  <consequence>
      <variable name="ATTENTION_LEVEL" />
      <operator symbol="*" />      
      <variable name="LOOK_AT" />
      <operator symbol="*" />
      <subconsequence>
        <variable name="LAST_BC" />
        <operator symbol="/" />
        <variable name="MAX_BC_INTERVALL" />
      </subconsequence>
  </consequence>

</rule> 

<rule name="NODS" type="activation" priority="8">

  <condition>
      <test var="state" op="==" val="1"/>
  </condition>


  <consequence>
      <variable name="ATTENTION_LEVEL" />
      <operator symbol="*" />      
      <variable name="LOOK_AT" />
      <operator symbol="*" />
      <subconsequence>
        <variable name="LAST_BC" />
        <operator symbol="/" />
        <variable name="MAX_BC_INTERVALL" />
      </subconsequence>
  </consequence>

</rule> 

<rule name="NODS" type="activation" priority="6">

  <condition>
      <test var="state" op="==" val="1"/>
      <operator symbol="or"/>
      <test var="state" op="==" val="-1"/>
  </condition>


  <consequence>
      <variable name="ATTENTION_LEVEL" />
      <operator symbol="*" />      
      <variable name="LOOK_AT" />
      <operator symbol="*" />
      <subconsequence>
        <variable name="LAST_BC" />
        <operator symbol="/" />
        <variable name="MAX_BC_INTERVALL" />
      </subconsequence>
  </consequence>

</rule> 

<rule name="POSES" type="activation" priority="6">

  <condition>
        <test var="Hx.motionless" op="more" val="2" />
        <operator symbol="and"/>
        <test var="Hy.motionless" op="more" val="2" />
        <operator symbol="and"/>
        <test var="Hz.motionless" op="more" val="2" />
  </condition>


  <consequence>
      <variable name="ATTENTION_LEVEL" />
      <operator symbol="*" />      
      <variable name="LOOK_AT" />
      <operator symbol="*" />
      <subconsequence>
        <variable name="LAST_BC" />
        <operator symbol="/" />
        <variable name="MAX_BC_INTERVALL" />
      </subconsequence>
  </consequence>

</rule> 
</implementation>

</backchannellibrary>
