=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/xmls/D_emotions.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<!ELEMENT emotion EMPTY>
<!ATTLIST emotion
	name CDATA #REQUIRED
	activation CDATA #REQUIRED
	evaluation CDATA #REQUIRED
	power CDATA #REQUIRED
>
<!ELEMENT emotions (emotion+)>

=== SEMAINE/SEMAINE-3.1/c++/src/Greta/Greta/bin/fd/efe/xmls/D_emotions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by radek (pszczolki) -->
<!DOCTYPE emotions SYSTEM "D_emotions.dtd">
<emotions>
	<emotion name="joy" activation="17.3" evaluation="42.2" power="12.5"/>
	<emotion name="distress" activation="-17.2" evaluation="-40.1" power="-52.4"/>
	<emotion name="happy-for" activation="17.3" evaluation="42.2" power="12.5"/>
	<emotion name="gloating" activation="40.0" evaluation="30.0" power="30.0"/>
	<emotion name="resentment" activation="0.0" evaluation="-40.0" power="-20.0"/>
	<emotion name="sorry-for" activation="-17.2" evaluation="-40.1" power="-52.4"/>
	<emotion name="hope" activation="20.0" evaluation="20.0" power="-10.0"/>
	<emotion name="fear" activation="14.8" evaluation="-44.4" power="-79.4"/>
	<emotion name="satisfaction" activation="-14.9" evaluation="33.1" power="12.2"/>
	<emotion name="relief" activation="3.0" evaluation="33.0" power="-3.0"/>
	<emotion name="fears-confirmed" activation="-30.0" evaluation="-50.0" power="-70.0"/>
	<emotion name="disappointment" activation="2.4" evaluation="-24.9" power="-37.2"/>
	<emotion name="pride" activation="30.0" evaluation="40.0" power="30.0"/>
	<emotion name="admiration" activation="27.0" evaluation="53.0" power="17.0"/>
	<emotion name="shame" activation="4.6" evaluation="-26.3" power="-62.3"/>
	<emotion name="reproach" activation="-3.0" evaluation="-30.0" power="43.0"/>
	<emotion name="liking" activation="-14.9" evaluation="33.1" power="12.2"/>
	<emotion name="disliking" activation="15.0" evaluation="-35.0" power="-10.0"/>
	<emotion name="gratutide" activation="20.0" evaluation="40.0" power="-30.0"/>
	<emotion name="anger" activation="34.0" evaluation="-35.6" power="20.0"/>
	<emotion name="gratification" activation="-14.9" evaluation="33.1" power="12.2"/>
	<emotion name="remorse" activation="4.6" evaluation="-26.3" power="-62.3"/>
	<emotion name="love" activation="1.2" evaluation="33.3" power="14.9"/>
	<emotion name="hate" activation="60.0" evaluation="-60.0" power="30.0"/>
	<emotion name="disgust" activation="-3.0" evaluation="-30.0" power="43.0"/>
	<emotion name="contempt" activation="-3.0" evaluation="-30.0" power="43.0"/>
	<emotion name="neutral" activation="0" evaluation="0" power="0"/>
	<emotion name="sadness" activation="-8.5" evaluation="-42.9" power="-55.3"/>
	<emotion name="worried" activation="-8.5" evaluation="-42.9" power="-55.3"/>
</emotions>
